lib/features/call/bloc/call_bloc.dart
lib/features/call/bloc/call_bloc.freezed.dart
lib/features/call/bloc/call_state.dart
lib/features/call/view/call_active_scaffold.dart
lib/features/call/view/call_active_thumbnail.dart
lib/features/call/widgets/rtc_stream_view.dart
lib/features/call/widgets/widgets.dart
screenshots/lib/data/call.dart

Due to the imperative controll of renderers lifecycle from logic components there is situation that happens when RTCVideoView tries to draw disposed renderer while rebuild happens in the gap described below.
```
await state.performOnActiveCall(event.callId, (activeCall) async {
await (await _peerConnectionRetrieve(activeCall.callId))?.close();
await activeCall.renderers.dispose();
await activeCall.renderers.local.srcObject?.dispose();
});
!!the gap!!
emit(state.copyWithPopActiveCall(event.callId));
```
So in this situation it cause null pointer exception on texture id of renderer.

Fix/rtc renderer disposed before UI

---

packages/data/app_database/lib/src/app_database.dart
packages/data/app_database/test/contacts_dao_test.dart

https://www.sqlite.org/faq.html#q18
The default configuration of SQLite only supports case-insensitive comparisons of ASCII characters. The reason for this is that doing full Unicode case-insensitive comparisons and case conversions requires tables and logic that would nearly double the size of the SQLite library. The SQLite developers reason that any application that needs full Unicode case support probably already has the necessary tables and functions and so SQLite should not take up space to duplicate this ability.
Instead of providing full Unicode case support by default, SQLite provides the ability to link against external Unicode comparison and conversion routines. The application can overload the built-in [NOCASE](https://www.sqlite.org/datatype3.html#collation) collating sequence …

feat: replace sqlite "like" command with "regexp" for utf-8 support

---

packages/data/app_database/lib/src/app_database.dart

Perform a clean downgrade of the database when the app is downgraded from a newer test flight version to an older production version.
This ensures that the database schema is compatible with the older version by removing all existing tables.

feat: add logic for database migration handling downgrade

---

lib/data/app_certificates.dart
lib/data/app_info.dart
lib/data/app_permissions.dart
lib/data/app_preferences.dart
lib/data/app_sound.dart
lib/data/app_themes.dart
lib/data/app_time.dart
lib/data/device_info.dart
lib/data/feature_access.dart
lib/data/package_info.dart
lib/data/secure_storage.dart
lib/data/session_cleanup_worker.dart

This change simplifies singleton initialization by condensing the setup logic into a single line per instance.
For example:
_appPreferences ??= await AppPreferences.init();
_appCertificates ??= await AppCertificates.init();
This ensures that the instances are initialized only once (if not already initialized) in a concise and readable manner.

refactor: change return type in data

---

lib/features/call/bloc/call_bloc.dart
lib/utils/utils.dart
lib/utils/webtrit_signaling_utils.dart

The signaling parsing logic is currently used in two places, so it has been centralized to a single location for better maintainability. In the future, it might be beneficial to move this logic to the signaling package for even greater modularity.

refactor: move signaling parsing to utils

---

lib/features/call/view/call_active_scaffold.dart
lib/features/call/view/call_screen.dart
lib/features/call/widgets/call_actions.dart
lib/features/call/widgets/call_info.dart

When the signaling has not been initialized or encounters an issue, we should disable interaction with the action button and display an appropriate status.

feat: improve signaling info on call screen

---

packages/webtrit_api/lib/src/webtrit_api_client.dart
packages/webtrit_signaling/lib/src/webtrit_signaling_client.dart

This pull request addresses an issue where a trailing slash (/) in the tenantUrl caused duplicate path segments in the generated URLs. The problem arose due to the inclusion of an empty string in the pathSegments list, leading to incorrect URL reconstruction.
What’s Changed
•	Updated the buildTenantUrl method to filter out empty segments from baseUrl.pathSegments using where((segment) => segment.isNotEmpty).
•	Ensured that removeRange correctly removes the tenant and tenantId segments without duplication.
•	Improved URL reconstruction to handle both scenarios (with and without a trailing slash).
What Happens Without This Fix
If the tenantUrl contains a trailing slash, the following issues occur:
•	The pathSegments includes an empty string ('') at the end, which disrupts the logic for …

fix: handle trailing slash in tenantUrl to prevent duplicate path segments

---

lib/features/login/features/login_embedded/view/login_embedded_screen.dart
lib/widgets/webview_scaffold.dart

Removed WebViewController from optional parameters to prevent breaking widget logic and reduce responsibility spreading

refactor: remove web view controller parameter from WebViewScaffold

---

lib/common/signaling_manager.dart

The decline call request was ignored because the Call ID was not found. This occurred due to _lines not being updated correctly
https://app.clickup.com/t/8696nabbp

fix: optimize active line handling and improve call log processing

---

lib/app/router/main_shell.dart
lib/common/signaling_manager.dart
lib/features/call/bloc/call_bloc.dart
lib/features/call/services/background_call_event_service.dart
lib/features/call/services/background_call_isolate.dart

Pleas check first: https://github.com/WebTrit/webtrit_callkeep/pull/49
This update handles cases where user actions on connections (e.g., accept or decline) don’t reach the server, potentially due to network issues. It provides proper handling for incoming, outgoing, and accepted calls, ensuring the application state remains consistent even if the server does not acknowledge these actions immediately.

feat: synchronize local connections with core

---

lib/common/common.dart
lib/common/filtered_logz_io_appender.dart
lib/common/remote_log_filter.dart
lib/data/app_logger.dart

Added functionality to the Logzio client to ignore specific logs, such as exceptions emitted in common logs when there is no internet connection. This enhancement prevents unnecessary noise in logs and improves log management during connectivity issues.

feat: extend Logzio appender to enable ignoring specific logs

---

lib/bootstrap.dart
lib/common/app_id_provider.dart
lib/common/common.dart
lib/data/app_info.dart
lib/data/app_logger.dart
lib/features/call/services/background_call_isolate.dart
lib/features/settings/features/about/bloc/about_bloc.dart
lib/features/settings/features/about/bloc/about_bloc.freezed.dart
lib/features/settings/features/about/bloc/about_state.dart
lib/features/settings/features/about/view/about_screen.dart
lib/l10n/app_localizations.g.dart
lib/l10n/app_localizations.g.mapper.dart
lib/l10n/app_localizations_en.g.dart
lib/l10n/app_localizations_it.g.dart
lib/l10n/app_localizations_uk.g.dart
lib/l10n/arb/app_en.arb
lib/l10n/arb/app_it.arb
lib/l10n/arb/app_uk.arb

- Move app ID retrieval to a dedicated App ID provider, allowing the application to function without Firebase when not needed and accommodating cases where Google services are unavailable.
- Integrate the app session identifier to enable targeted filtering in the remote logging system.

feat: enable use of app session identifier in remote logging system

---

android/gradle.properties
android/gradle/wrapper/gradle-wrapper.properties
android/settings.gradle

[✓] Flutter (Channel stable, 3.27.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)

build: upgrade Kotlin and Gradle plugin for Flutter 3.27.1 compatibility

---

lib/features/call/widgets/call_actions.dart
lib/features/keypad/widgets/actionpad.dart

I would like to provide the icon size from the ThemeProvider, but until the widget is not rendered, we cannot determine the font size to maintain the current logic.

fix: correct icon size on the action pad after Flutter upgrade

---

lib/app/router/main_shell.dart
lib/bootstrap.dart
lib/data/app_logger.dart
lib/data/package_info.dart
lib/features/autoprovision/cubit/autoprovision_cubit.dart
lib/features/autoprovision/view/autoprovision_screen_page.dart
lib/features/call/services/background_call_isolate.dart
lib/features/embedded/view/embedded_screen.dart
lib/features/log_records_console/cubit/log_records_console_cubit.dart
lib/features/log_records_console/view/log_records_console_screen_page.dart
lib/features/login/cubit/login_cubit.dart
lib/features/login/features/login_embedded/view/login_embedded_screen.dart
lib/features/login/view/login_router_page.dart
lib/features/main/bloc/main_bloc.dart
lib/features/main/view/main_screen_page.dart
lib/features/settings/features/about/view/about_screen_page.dart
lib/features/settings/features/about/view/webview_about_screen.dart
lib/features/settings/features/help/view/help_screen.dart
lib/features/settings/features/self_config/view/self_config_screen.dart
lib/features/terms_conditions/view/terms_conditions_screen.dart
lib/main.dart
lib/widgets/webview_scaffold.dart

- Use inheritance to provide the data class instead of using singleton access.
- Use constructor injection to enable mocking of data.
- Refactor PackageInfo to allow data mocking.

refactor: data class dependency injection

---

lib/bootstrap.dart
lib/data/device_info.dart
lib/features/call/services/background_call_isolate.dart
lib/features/embedded/view/embedded_screen.dart
lib/features/login/features/login_embedded/view/login_embedded_screen.dart
lib/features/permissions/view/permissions_screen_page.dart
lib/features/settings/features/about/view/webview_about_screen.dart
lib/features/settings/features/help/view/help_screen.dart
lib/features/settings/features/self_config/view/self_config_screen.dart
lib/features/terms_conditions/view/terms_conditions_screen.dart
lib/main.dart
lib/utils/user_agent.dart
lib/utils/utils.dart
lib/widgets/webview_scaffold.dart

- Added an interface for DeviceInfo to enable mock data creation for testing
- Provided DeviceInfo via an InheritedWidget instead of accessing it through a singleton
- Moved user agent handling to the WebView constructor and a utility function for generating it based on the DeviceInfo data class

refactor: update device info and provide user agent via utility

---

assets/themes/original.widget.dark.config.json
lib/bootstrap.dart
lib/data/feature_access.dart
lib/features/embedded/view/embedded_screen.dart
packages/webtrit_appearance_theme/lib/models/app_config.dart
packages/webtrit_appearance_theme/lib/models/app_config.freezed.dart
packages/webtrit_appearance_theme/lib/models/app_config.g.dart
screenshots/lib/screenshots/login_mode_select_screen_screenshot.dart
screenshots/lib/screenshots/login_signup_screen_screenshot.dart
screenshots/lib/widgets/screenshot_app.dart

- Aligned the default dark mode scheme with the light mode for consistency.
- Removed redundant theme data initialization to clean up the code.
- Resolved theme data warnings for a more robust implementation.
- Standardized hex color values to upper case for uniformity.
- Added the correct localization key for the default title in the webtrit_appearance_theme.

refactor: clean up theme data and localization improvements

---

pubspec.lock
pubspec.yaml

Rebase the latest commits from the original main branch for support Flutter 3.29

chore: webrtc sources update 27.02.25

---

lib/features/call/bloc/call_bloc.dart

fix: undefined line error on 3.29 update caused by new sync native bindings, that cause start of __onCallPerformEventStarted execution before new call is emited in __onCallControlEventStarted

fix: undefined line error on 3.29 update

---

lib/app/app_bloc_observer.dart
lib/app/router/app_router_observer.dart
lib/blocs/external_contacts_sync/external_contacts_sync_bloc.dart
lib/blocs/local_contacts_sync/local_contacts_sync_bloc.dart
lib/features/call_to_actions/bloc/call_to_actions_cubit.dart
lib/features/main/widgets/main_screen_route_observer.dart
lib/features/messaging/services/chats_outbox_worker.dart
lib/features/messaging/services/chats_sync_worker.dart
lib/features/push_tokens/bloc/push_tokens_bloc.dart
lib/features/session_status/bloc/session_status_cubit.dart
lib/widgets/safe_network_image.dart
packages/webtrit_signaling/lib/src/webtrit_signaling_client.dart

- Downgraded BlocObserver logs from fine to finest
- Reduced log level for WebSocket data events
- Downgraded image loading error log from warning to finest
- Replaced route observer logs with formatted route names
- Lowered push token logs from info to fine
- Reduced log level for ChatsSyncWorker and ChatsOutboxWorker
- Downgraded MainScreenNavigatorObserver logs to finest
- Lowered flavor check logs to finest
- Reduced verbosity in ExternalContactsSync logs

chore: reduce logging verbosity across core components

---

lib/app/router/main_shell.dart
lib/bootstrap.dart
lib/common/logging/logzio_logging_service.dart
lib/data/app_logger.dart
lib/features/call/services/services_isolate.dart
lib/main.dart

AppLogger still generates labels upon instance creation, ensuring initial context is available.
However, a new method has been added to allow regenerating these labels dynamically — for example, after user authorization when additional context (e.g. core URL, tenant id) becomes available.

feat: add additonal labels for log filtering

---

lib/app/router/main_shell.dart
lib/features/call/bloc/call_bloc.dart
lib/features/call/utils/sdp_mod_builder.dart
lib/features/call/utils/sdp_sanitizer.dart
lib/features/call/utils/utils.dart

- Introduced `SdpSanitizer` abstraction and `RemoteSdpSanitizer` implementation for cleaning unsupported or invalid SDP fields.
- Integrated `sdpSanitizer` into call flow to sanitize remote SDP before applying it via `setRemoteDescription`.
- Ensures better compatibility with services that do not support certain parameters

feat: add and integrate RemoteSdpSanitizer for remote SDP cleanup

---

lib/features/call/bloc/call_state.dart

Allows showing video icon for incoming calls even before the remote stream is available
Note: switching from video to audio before answer is not yet handled and requires signaling update

fix: fallback to video flag when remote stream is unavailable to indicate original incoming call type

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/res/xml/network_security_config.xml
dart_define.json

Enable configuration of allowed cleartext HTTP domains on Android via dart-define

feat: support defining cleartext HTTP allowed domains via dart-define

---

assets/themes/app.config.json
lib/data/feature_access.dart
lib/l10n/app_localizations.g.dart
lib/l10n/app_localizations.g.mapper.dart
lib/l10n/app_localizations_en.g.dart
lib/l10n/app_localizations_it.g.dart
lib/l10n/app_localizations_uk.g.dart
lib/l10n/arb/app_en.arb
lib/l10n/arb/app_it.arb
lib/l10n/arb/app_uk.arb

•	Added translations for voicemail and settings updates
•	Updated app configuration
•	Implemented logic to skip empty groups in the settings menu

feat: move voicemail item to services group

---

lib/extensions/audio_player_extension.dart
lib/extensions/extensions.dart
lib/features/settings/features/voicemail/bloc/voicemail_cubit.dart
lib/features/settings/features/voicemail/widgets/audio_view.dart

•	Removed cache file handling in LockCachingAudioSource on iOS to prevent crashes
•	Added safe disposal of AudioPlayer within the view
•	Ensured safe state emission in VoicemailCubit

fix: add possibily play voicemail on iOS

---

lib/data/feature_access.dart
lib/features/call/view/call_active_scaffold.dart
lib/features/call/view/call_screen.dart
lib/features/call/view/call_screen_page.dart
lib/features/call/widgets/call_actions.dart
lib/features/contact/view/contact_screen_page.dart
lib/features/favorites/view/favorites_screen_page.dart
lib/features/keypad/view/keypad_screen_page.dart
lib/features/recent/view/recent_screen_page.dart
lib/features/recents/view/recents_screen_page.dart
lib/models/feature_access/call_config.dart
lib/models/feature_access/feature_access.dart

Updates the onCameraChanged handler to respect CallConfig.isVideoCallEnabled. If video calls are disabled in the config, the camera toggle becomes inactive in the UI, ensuring consistent behavior with feature availability.

feat: disable camera toggle when video calls are not enabled via CallConfig

---

lib/features/call/view/call_shell.dart
pubspec.lock
pubspec.yaml
screenshots/pubspec.lock

The auto_route version 10.0.1 introduces a critical issue with nested routes and ReevaluateListenable.
When ReevaluateListenable.stream(appBloc.stream) triggers (e.g. after changing language), the navigation stack breaks due to a key reservation error.

fix: downgrade auto route to 9.3.0+1

---

ios/Podfile.lock
lib/app/router/app_router.dart
pubspec.lock
pubspec.yaml

Removes the outdated workaround that manually triggered innerRouter.reevaluateGuards() inside onAppShellRouteGuardNavigation. This is no longer needed in auto_route >= 10.0.1.
[Related issue: auto_route_library#2196](https://github.com/Milad-Akarie/auto_route_library/issues/2196)

refactor: remove obsolete innerRouter.reevaluateGuards workaround from AppShellRoute guard

---

android/app/build.gradle
android/app/src/deeplinks/AndroidManifest.xml
android/app/src/main/AndroidManifest.xml
build.config
dart_define.json
lib/app/view/app.dart

This PR introduces flavors to enable controlled merging of AndroidManifests. It ensures Play Store compatibility by eliminating warnings related to unconfigured or partially configured deeplinks.
This is the first step toward a broader flavor system, starting with deeplinks and SMS-triggered permissions. Defining flavors allows us to isolate and include manifest declarations (e.g. <intent-filter>, <receiver>) only when required by specific clients.
Flavors cannot be selected via dart-define alone — they must be passed explicitly using the --flavor flag during the build. To address this, we now handle flavor resolution via Makefile logic.
Follow-ups
•	This change requires updating external build tools, such as: [webtrit_phone_builder](https://github.com/WebTrit/webtrit_phone_builder/pull/8) …

feat: add flavor-based control to enable or disable Android deeplinks via dart-define configuration

---

README.md
docs/build.md
docs/flavors.md

Add documentation explaining flavors and how to build the project. The “Make commands” section in the README is outdated and should be cleaned up along with the local makefile. Perform cleanup after merge.

feat: add build flavors and update documentation for build process

---

lib/theme/factory/theme_data/tab_bar_theme_data_factory.dart
lib/theme/factory/theme_style_factory_provider.dart
lib/theme/theme_provider.dart

Updated the `TabBarThemeDataFactory` implementation to return `TabBarThemeData` instead of the deprecated `TabBarTheme`, aligning with Flutter 3.32 (stable channel) requirements.

fix: migrate TabBarTheme to TabBarThemeData for Flutter 3.32 Stable

---

docs/embedded_pages.md
lib/widgets/web_view_container.dart

Introduces a custom URI scheme (app://openInExternalBrowser?url=...) to explicitly mark links that should be opened outside of the WebView using the system browser. This improves link handling by separating internal navigation from external actions.

feat: add support for opening external links from WebView

---

docs/embedded_pages.md
lib/widgets/web_view_container.dart

This change allows the embedded web page to receive layout-related data such as status bar height, navigation bar height, device pixel ratio, and brightness (dark mode).

feat: inject MediaQuery data via window.onMediaQueryReady callback

---

lib/features/settings/features/about/bloc/about_bloc.dart
lib/features/settings/features/about/bloc/about_bloc.freezed.dart
lib/features/settings/features/about/bloc/about_state.dart
lib/features/settings/features/about/view/about_screen.dart
lib/features/settings/features/about/view/about_screen_page.dart
lib/l10n/app_localizations.g.dart
lib/l10n/app_localizations.g.mapper.dart
lib/l10n/app_localizations_en.g.dart
lib/l10n/app_localizations_it.g.dart
lib/l10n/app_localizations_uk.g.dart
lib/l10n/arb/app_en.arb
lib/l10n/arb/app_it.arb
lib/l10n/arb/app_uk.arb

Since we currently don’t have a label to indicate the environment, this feature allows detecting the environment based on the embedded application links.

feat: add UI to preview embedded application links

---

packages/webtrit_api/lib/src/exceptions.dart
packages/webtrit_api/test/request_failure_test.dart

When debugging multiple log entries, it was difficult to identify which request a particular RequestFailure was related to.
To improve traceability, this PR enhances the toString() method to include the requestId

refactor: improve RequestFailure.toString output with structured format

---

lib/app/notifications/models/notification.dart
lib/app/router/main_shell.dart
lib/features/call/call.dart
lib/features/call/controllers/call_controller.dart
lib/features/call/controllers/controllers.dart
lib/features/call_routing/cubit/call_routing_cubit.dart
lib/features/contact/view/contact_screen.dart
lib/features/favorites/view/favorites_screen.dart
lib/features/keypad/view/keypad_view.dart
lib/features/recents/view/recents_screen.dart
lib/main.dart
lib/services/connectivity_service.dart
lib/services/services.dart

**Problem**
If the app is initialized without an internet connection, and during that time the CallRoutingCubit attempts to load data, it fails with an error and never retries again.
As a result, even if the internet becomes available later, any attempt to place a call is silently ignored due to this check:
<pre>
final callRoutingCubit = context.read&lt;CallRoutingCubit&gt;();
final callRoutingState = callRoutingCubit.state;
if (callRoutingState == null) return;
</pre>
**Solution**
•	Introduced a global ConnectivityService to monitor network status.
•	CallRoutingCubit now automatically retries to fetch data when internet connectivity is restored.
•	Moved duplicated call logic into a centralized CallController class for better reuse and maintainability.

fix: retry CallRoutingCubit load on network restore and handle missing state

---

lib/features/contacts_agreement/view/contacts_agreement_screen.dart
lib/features/permissions/view/permissions_screen.dart
lib/features/permissions/widgets/permission_tips.dart
lib/features/user_agreement/view/user_agreement_screen.dart
lib/widgets/inert_safe_area.dart
lib/widgets/widgets.dart

This PR fixes a UI issue where the navigation bar was overlapping with Continue buttons in various screens. The solution introduces a new InertSafeArea widget that provides controlled safe area padding only at the bottom of the screen.
Creates a new InertSafeArea widget that extends SafeArea with customized defaults
Applies bottom safe area padding to prevent navigation bar overlap in multiple screens
Updates widget exports to include the new component

fix: prevent navigation bar from overlapping Continue button

---

lib/theme/factory/styles/about_screen_style_factory.dart
lib/theme/factory/styles/logo_assets_factory.dart
lib/theme/factory/styles/onboarding_logo_style_factory.dart
lib/theme/factory/styles/onboarding_picture_logo_style_factory.dart
packages/webtrit_appearance_theme/lib/models/features_config/metadata.dart
packages/webtrit_appearance_theme/lib/models/models.dart
packages/webtrit_appearance_theme/lib/models/resources/image_source.dart
packages/webtrit_appearance_theme/lib/models/resources/image_source.freezed.dart
packages/webtrit_appearance_theme/lib/models/resources/image_source.g.dart
packages/webtrit_appearance_theme/lib/models/resources/resources.dart
packages/webtrit_appearance_theme/lib/models/theme_page_config.dart
packages/webtrit_appearance_theme/lib/models/theme_page_config.freezed.dart
packages/webtrit_appearance_theme/lib/models/theme_page_config.g.dart
packages/webtrit_appearance_theme/lib/models/theme_widget_config.dart
packages/webtrit_appearance_theme/lib/models/theme_widget_config.freezed.dart
packages/webtrit_appearance_theme/lib/models/theme_widget_config.g.dart

This PR refactors image source handling by unifying image references into a single ImageSource structure. The refactor introduces a new ImageSource class that encapsulates URI, ID, reference type, and metadata for images, while maintaining backward compatibility with the existing uri field through deprecation.
Introduces a new ImageSource class with comprehensive documentation and metadata support
Updates all image configuration classes to use the new ImageSource structure while keeping deprecated uri fields
Modifies factory classes to handle both new and deprecated image source patterns

refactor: unify image source into a single structure

---

assets/themes/original.page.dark.config.json
assets/themes/original.page.light.config.json
docs/page_configuration.md
lib/features/call/view/call_active_scaffold.dart
lib/features/call/view/call_screen_style.dart
lib/features/call/widgets/call_actions.dart
lib/theme/factory/styles/call_actions_style_factory.dart
lib/theme/factory/styles/call_screen_style_factory.dart
lib/theme/factory/theme_style_factory_provider.dart
lib/theme/styles/app_bar_style.dart
packages/webtrit_appearance_theme/analysis_options.yaml
packages/webtrit_appearance_theme/lib/models/theme_page_config.dart
packages/webtrit_appearance_theme/lib/models/theme_page_config.freezed.dart
packages/webtrit_appearance_theme/lib/models/theme_page_config.g.dart
packages/webtrit_appearance_theme/lib/models/theme_widget_config.dart
packages/webtrit_appearance_theme/lib/models/theme_widget_config.freezed.dart
packages/webtrit_appearance_theme/lib/models/theme_widget_config.g.dart

This PR introduces comprehensive enhancements to the call screen theming system, adding a new CallPageActionsConfig for styling call action buttons with support for disabled states, updating the documentation, and deprecating legacy configurations while maintaining backward compatibility.
Adds new CallPageActionsConfig and CallScreenActionsStyle for better call action button theming
Extends ElevatedButtonWidgetConfig with disabled foreground/background color properties
Updates documentation with detailed examples and restructures page configuration guide

feat: add new CallScreen style factory with actions support, JSON schema updates, and docs

---

lib/features/embedded/view/embedded_screen.dart
lib/features/embedded/view/embedded_screen_page.dart
lib/features/embedded/view/embedded_tab_page.dart
lib/widgets/webview/webview_injection_builders.dart

This PR refactors embedded page handling by reorganizing console logging injection and adjusting default log capture behavior. The changes ensure console logging is initialized first to capture logs from other injections and temporarily hardcodes log capture to be enabled.
Reordered console logging injection to be first in the injection strategy list
Changed default enableLogCapture from false to true and hardcoded it in embedded pages
Reorganized field declarations in EmbeddedScreen class

refactor: clean up embedded page handling
