WebTrit/webtrit_phone

lib/app/constants.dart
lib/features/keypad/widgets/actionpad.dart
lib/features/keypad/widgets/keypad.dart

Added limit for keypads items, it's fix most not covered screen size

fix: add limit for keypad size

---

lib/features/contacts/view/contacts_screen.dart
lib/features/recents/view/recents_screen.dart

Perhaps it is worth making a common constant

Change tab width

---

screenshots/lib/main.dart
screenshots/lib/screenshots/login_screen_screenshot.dart

refactor(screenshots): move greeting message to constructor of LoginScreenScreenshot

---

README.md
android/app/build.gradle
android/app/src/main/AndroidManifest.xml
dart_define.json
ios/Runner/Info.plist
ios/Runner/Runner.entitlements

Links:
- https://docs.flutter.dev/ui/navigation/deep-linking
- https://docs.flutter.dev/cookbook/navigation/set-up-app-links
- https://docs.flutter.dev/cookbook/navigation/set-up-universal-links

Setup deep linking

---

screenshots/android/app/build.gradle
screenshots/integration_test/take_screenshots_test.dart
screenshots/lib/main.dart
screenshots/lib/router.dart
screenshots/lib/router.gr.dart
screenshots/lib/widgets/screenshot_app.dart
screenshots/pubspec.yaml

Test launch fixes, android launch fixes, router context fixes, removed go_router.

fixes(screenshots app): test launch fixes, android launch fixes, router context fixes, removed go_router.

---

lib/features/autoprovision/cubit/autoprovision_cubit.dart
lib/features/autoprovision/cubit/autoprovision_state.dart
lib/features/call/view/call_shell.dart

Attention dont accept before fix "401 session missing" from backend side!!

Fix (autoprovision): token exchange before confirmation

---

pubspec.yaml

build: update app version; adjust allowed changes as per ClickUp task [4hq31-14872](https://app.clickup.com/4775009/docs/4hq31-5212/4hq31-14872)

build: update app version;

---

pubspec.yaml

https://app.clickup.com/4775009/docs/4hq31-5212

build: update app version

---

lib/features/call/bloc/call_bloc.dart
lib/features/call/models/notification.dart
lib/l10n/app_localizations.g.dart
lib/l10n/app_localizations_en.g.dart
lib/l10n/app_localizations_it.g.dart
lib/l10n/app_localizations_uk.g.dart
lib/l10n/arb/app_en.arb
lib/l10n/arb/app_it.arb
lib/l10n/arb/app_uk.arb

Implement warning for blind transfer attempt when already on the active line

feat: implement warning for blind transfer

---

lib/features/call/view/call_shell.dart

conditionally pop to root screen based on isBlingTransferInitiated state

feat: conditionally pop to root screen based on isBlingTransferInitiated state

---

lib/features/call/bloc/call_bloc.dart

Callkeep missed call notification support by forwarding CallkeepEndCallReason.unanswered for such cases and introduce additional displayName param for determine who was call.
Attention: linked with https://github.com/WebTrit/webtrit_callkeep/pull/20 pr and should be merged together.

feat: callkeep missed call notification support 

---

lib/features/push_tokens/bloc/push_tokens_bloc.dart
lib/features/push_tokens/bloc/push_tokens_bloc.freezed.dart
lib/features/push_tokens/bloc/push_tokens_event.dart
lib/features/push_tokens/bloc/push_tokens_state.dart
lib/utils/backoff_retries.dart
lib/utils/utils.dart

https://app.clickup.com/t/8696kb0uw

fix: add retry logic for service token fetch and token upload status tracking

---

lib/bootstrap.dart
lib/common/callkeep_logs.dart
lib/common/common.dart
lib/common/fcm_isolate_database.dart

refactor: move isolate db wrapper and CallKeep log callback to common package

---

lib/widgets/webview_scaffold.dart

For case when need some wrapper do web view  and ignore toolbar

feat: add builder for WebView widget

---

assets/themes/app.config.json
assets/themes/custom_signup.html
lib/app/assets.gen.dart
lib/app/router/app_router.dart
lib/app/router/app_router.gr.dart
lib/features/login/cubit/login_cubit.dart
lib/features/login/features/login_signup/extension/extensions.dart
lib/features/login/features/login_signup/extension/web_resource_error_l10n.dart
lib/features/login/features/login_signup/login_signup.dart
lib/features/login/features/login_signup/view/login_signup_embedded_request_screen.dart
lib/features/login/features/login_signup/view/login_signup_embedded_request_screen_page.dart
lib/features/login/features/login_signup/view/login_signup_router_page.dart
lib/features/login/features/login_signup/widgets/embedded_request_error.dart
lib/features/login/features/login_signup/widgets/widgets.dart
lib/features/login/view/login_mode_select_screen.dart
lib/features/login/view/login_mode_select_screen_page.dart
packages/webtrit_api/lib/src/models/session_user_credential.dart
packages/webtrit_api/lib/src/models/session_user_credential.freezed.dart
packages/webtrit_api/lib/src/models/session_user_credential.g.dart
packages/webtrit_api/lib/src/webtrit_api_client.dart
screenshots/lib/screenshots/login_mode_select_screen_screenshot.dart

•	Updated app schema to support both URLs and local paths as resources.
•	Added a custom signup page where users can collect data
•	Upon confirmation, data is sent via POST to /User, with the response driving the next steps in the flow.

feat: improve embedded signup

---

lib/features/call/bloc/call_bloc.dart
lib/features/call/extensions/processing_status.dart
lib/features/call/models/active_call_status.dart
lib/features/call/widgets/call_actions.dart
lib/l10n/app_localizations.g.dart
lib/l10n/app_localizations_en.g.dart
lib/l10n/app_localizations_it.g.dart
lib/l10n/app_localizations_uk.g.dart
lib/l10n/arb/app_en.arb
lib/l10n/arb/app_it.arb
lib/l10n/arb/app_uk.arb

It doesn't feel as good on performance phones as it does on budget phones.

feat: add additional status to inform the user about the answering process

---

lib/features/call/view/call_active_scaffold.dart
lib/features/messaging/extensions/theme.dart
lib/features/messaging/features/chat_conversation/widgets/dialog_info.dart
lib/features/messaging/features/chat_conversation/widgets/group_info.dart
lib/features/messaging/features/chat_conversation_builder/view/builder_stages/dialog_contact_selection_view.dart
lib/features/messaging/features/chat_conversation_builder/view/builder_stages/group_contacts_selection_view.dart
lib/features/messaging/features/chat_conversation_builder/view/builder_stages/group_fill_info_view.dart
lib/features/messaging/features/chat_conversation_builder/view/chat_conversation_builder_view.dart
lib/features/messaging/features/conversations/widgets/chat_conversations_tile.dart
lib/features/messaging/features/conversations/widgets/sms_conversations_tile.dart
lib/features/messaging/features/sms_conversation_builder/view/sms_conversation_builder_view.dart
lib/features/messaging/widgets/scroll_to_bottom.dart
lib/features/settings/widgets/session_status_list_tile.dart
lib/theme/theme_provider.dart
lib/widgets/keypad_key_button.dart

https://docs.flutter.dev/release/breaking-changes/wide-gamut-framework#opacity

feat: migrate from withOpacity to withValues(alpha)

---

lib/blocs/external_contacts_sync/external_contacts_sync_bloc.dart
lib/blocs/local_contacts_sync/local_contacts_sync_bloc.dart
lib/features/contact/bloc/contact_bloc.dart
lib/features/contact/bloc/contact_bloc.freezed.dart
lib/features/contact/bloc/contact_state.dart
lib/features/contact/view/contact_screen.dart
lib/features/keypad/cubit/keypad_cubit.dart
lib/mappers/drift/contacts_mapper.dart
lib/repositories/contacts/contacts_repository.dart
packages/data/app_database/lib/src/app_database.g.dart
packages/data/app_database/lib/src/daos/contact_phones_dao.dart
packages/data/app_database/lib/src/daos/contacts_dao.dart
packages/data/app_database/lib/src/daos/contacts_dao.g.dart
packages/data/app_database/test/contacts_dao_test.dart

Contains refactoring of legacy contacts data structure, that leads to use contact entity separately of their phones and emails so its produce bugs, inconsistency and confusing.

refactor: contact db structure

---

lib/app/router/app_router.dart
lib/app/router/main_shell.dart
lib/blocs/app/app_bloc.dart
lib/blocs/app/app_bloc.freezed.dart
lib/blocs/app/app_event.dart
lib/blocs/app/app_state.dart
lib/data/app_preferences.dart
lib/features/contacts_agreement/view/contacts_agreement_screen.dart
lib/features/permissions/cubit/permissions_cubit.dart
lib/features/user_agreement/view/user_agreement_screen.dart
screenshots/lib/mocks/mock_app_bloc.dart

- Refactored user agreement method signatures for better consistency and clarity across the codebase.
- Added Documentation

refactor: improve agreement handling with updated method signatures and added documentation

---

lib/widgets/leading_avatar.dart

Change avatar lyout from layered to hierarhical to avoid bug with transparent images and improove memory consumption

fix: avatar layered to hierarhical layout

---

screenshots/lib/mocks/mock_self_config_cubit.dart
screenshots/lib/mocks/mocks.dart
screenshots/lib/screenshots/main_screen_screenshot.dart
screenshots/lib/screenshots/setting_screen_screenshot.dart

- Enable dynamic UI changes in the configurator using the provided FeatureAccess.
- Add missing mock bloc for the settings screen.

feat: screenshots feature access and mock config

---

lib/features/login/features/login_signup/view/login_signup_embedded_request_screen.dart
lib/widgets/webview_scaffold.dart

Enable support for screens with WebView in the configurator

feat: add conditional WebView support for web platform using `kIsWeb`

---

assets/themes/app.config.json
lib/data/feature_access.dart
packages/webtrit_appearance_theme/lib/converters/bottom_menu_tab_type_converter.dart
packages/webtrit_appearance_theme/lib/converters/converters.dart
packages/webtrit_appearance_theme/lib/converters/uri_converter.dart
packages/webtrit_appearance_theme/lib/models/app_config.dart
packages/webtrit_appearance_theme/lib/models/app_config.freezed.dart
packages/webtrit_appearance_theme/lib/models/app_config.g.dart
packages/webtrit_appearance_theme/lib/models/bottom_menu_tab_type.dart
packages/webtrit_appearance_theme/lib/models/models.dart
packages/webtrit_appearance_theme/lib/parsers/bottom_menu_tab_scheme_parser.dart
packages/webtrit_appearance_theme/lib/parsers/parsers.dart
packages/webtrit_appearance_theme/pubspec.yaml
screenshots/lib/mocks/mock_login_cubit.dart
screenshots/lib/screenshots/login_signup_screen_screenshot.dart
screenshots/lib/widgets/screenshot_app.dart

- Unified feature handling by using a single embedded class for all features.
- Optimized and streamlined representation classes for better maintainability and performance.
- Actualize screenshots

refactor: clean up feature scheme

---

lib/features/call/bloc/call_bloc.dart

Fix for multi line calls thats drops active call if it not hold before making new call

fix: multiline call drop if active call held'nt

---

lib/theme/theme_provider.dart
packages/webtrit_appearance_theme/lib/models/theme_page_config.dart
packages/webtrit_appearance_theme/lib/models/theme_page_config.freezed.dart
packages/webtrit_appearance_theme/lib/models/theme_page_config.g.dart

Minor code style adjustments and add field to override login picture

chore: improve theme feature

---

lib/features/push_tokens/bloc/push_tokens_bloc.dart

Ensure FCM token is also sent on iOS

fix: ensure FCM token is also sent on iOS

---

assets/themes/app.config.json
lib/extensions/extensions.dart
lib/extensions/uri_extension.dart
lib/features/login/features/login_signup/view/login_signup_embedded_request_screen_page.dart
lib/theme/extension/string_ext.dart
lib/theme/models/models.dart
lib/theme/models/resource_loader.dart
lib/theme/models/theme_asset.dart

- extract URI parsing logic into a separate class for reuse with other asset resources

refactor: improve URI handling and simplify embedded resources management

---

Makefile
README.md
doc/launch_assets.md

Add Makefile for launch script to prepare launch and splash assets
Add doc

feat: add Makefile for launch script to prepare assets and include documentation

---

doc/localization.md
makefile

Add Makefiles to simplify command usage, update documentation, and add flag for pushing new keys as unreviewed

refactor: update localization flow

---

assets/themes/app.config.json
lib/data/feature_access.dart
lib/features/embedded/view/embedded_screen_page.dart
lib/features/settings/view/settings_screen.dart
lib/features/user_agreement/view/user_agreement_screen_page.dart
lib/models/feature_access/config_data.dart
packages/webtrit_appearance_theme/lib/models/features_config/embedded_resource.dart
packages/webtrit_appearance_theme/lib/models/features_config/embedded_resource.freezed.dart
packages/webtrit_appearance_theme/lib/models/features_config/embedded_resource.g.dart
packages/webtrit_appearance_theme/lib/models/features_config/embedded_resource_type.dart
packages/webtrit_appearance_theme/lib/models/features_config/features_config.dart
screenshots/lib/screenshots/privacy_screen_screenshot.dart

Add the ability to reuse common embedded resources if they are shared across multiple features; update documentation.

feat: improve embedded resources flow

---

packages/data/app_database/lib/src/daos/chats_dao.dart
packages/data/app_database/lib/src/daos/sms_dao.dart

adds ability to count unread messages for unvisited conversations

fix(messaging): unread count for unvisited conversations

---

android/.gitignore
lib/features/autoprovision/view/autoprovision_screen_page.dart
lib/features/messaging/features/conversations/cubit/chat_conversations_cubit.dart
lib/features/recents/extensions/direction_converting.dart
lib/l10n/app_localizations_en.g.dart
lib/l10n/app_localizations_it.g.dart
lib/l10n/app_localizations_uk.g.dart
lib/pre_bootstrap/web.dart
lib/theme/extension/theme_json_serializable.dart
lib/theme/factory/theme_data/input_decoration_theme_data_factory.dart
lib/theme/theme_provider.dart
lib/utils/backoff_retries.dart
packages/data/app_database/lib/app_database.dart
screenshots/lib/router.gr.dart
screenshots/lib/widgets/screenshot_app.dart

Remove deprecated components, imports, and unused code

chore: clean up project

---

lib/features/call/bloc/call_bloc.dart

Add missing log for failed registration status with error code and reason

feat: add logging for failed registration status with error code and reason

---

lib/features/call/widgets/call_actions.dart

adds strikethrought icons according to current state of call action

feat: call actions strikethrough

---

ios/Podfile.lock
pubspec.lock
pubspec.yaml

- actualize firebase dependency

feat: update Firebase dependency to latest version

---

lib/features/call/bloc/call_bloc.dart

- Implemented logic to detect local calls absent from the signaling state.
- Automatically ends such calls via CallKeep to align with signaling state.

feat: synchronize local calls with signaling state to end stale calls

---

lib/features/call/utils/sdp_mod_builder.dart
lib/features/call/utils/sdp_munger.dart

Fix for error on setRemoteDescription call when audio min bitrate setted under 64kbps without opus codec support.

fix: non opus min bitrate fix

---

assets/themes/app.config.json
lib/data/app_preferences.dart
lib/data/feature_access.dart
lib/features/call/utils/peer_connection_policy_applier.dart
lib/features/settings/features/media_settings/widgets/peer_connection_settings_section.dart
lib/mappers/json/negotiation_settings_mapper.dart
lib/models/negotiation_settings.dart
lib/models/peer_connection_settings.dart
packages/webtrit_appearance_theme/lib/models/features_config/app_config.dart
packages/webtrit_appearance_theme/lib/models/features_config/app_config.freezed.dart
packages/webtrit_appearance_theme/lib/models/features_config/app_config.g.dart

• Replaced enum with boolean since no other types are expected for this case
• Simplified logic for setting the initial default value
• Streamlined UI for selecting this option

refactor: simplify inactive track option flow

---

lib/app/assets.gen.dart
lib/app/router/app_router.dart
lib/app/router/app_router.gr.dart
lib/features/call/bloc/call_bloc.freezed.dart
lib/features/call/view/call_shell.dart
lib/l10n/app_localizations.g.mapper.dart
lib/l10n/l10n.dart
pubspec.lock
pubspec.yaml

• Updated auto_route to the latest version
• Upgraded related dependencies to maintain compatibility
• Migrated codebase to align with the new auto_route API
• Handled null pointer issues in l10n parsing logic
**Reason**: Found a bug with navigation behavior related to embedded pages; decided to fix it by upgrading to the latest version

chore: update autorouter dependency

---

lib/features/call/utils/sdp_mod_builder.dart

Add validation in _fixInvalidAudioBitrate to avoid overriding b=AS:0, and ensure bitrate is only updated when below the required minimum for active codecs. This prevents issues when codecs like Opus are removed from the SDP but bitrate values remain incompatible.

fix: preserve valid inbound audio bitrate in SDP when within codec limits

---

lib/theme/models/resource_loader.dart

Add support for HTTP scheme URLs in NetworkResourceLoader

refactor: replace scheme string with supportedSchemes list for clarity

---

lib/data/app_permissions.dart
lib/features/permissions/cubit/permissions_cubit.dart

Add additional logs for permission feature with log level to INFO to ensure these logs are more noticeable without being considered spam. Since this feature is not frequently active.

feat: add additional logs for permission feature

---

lib/data/app_permissions.dart
lib/features/permissions/cubit/permissions_cubit.dart

Improves handling of special permission settings with fallback and adds documentation.
Depend from: https://github.com/WebTrit/webtrit_callkeep/pull/85

fix: improve special permission settings handling with fallback

---

assets/themes/app.config.json
lib/app/router/app_router.gr.dart
lib/app/view/app.dart
lib/data/feature_access.dart
lib/features/login/cubit/login_cubit.dart
lib/features/login/cubit/login_cubit.freezed.dart
lib/features/login/cubit/login_state.dart
lib/features/login/features/login_signup/view/login_signup_embedded_request_screen_page.dart
lib/features/login/features/login_signup/view/login_signup_router_page.dart
lib/features/login/view/login_mode_select_screen.dart
lib/features/login/view/login_mode_select_screen_page.dart
lib/features/login/view/login_router_page.dart
lib/features/login/widgets/login_mode_action_button.dart
lib/features/login/widgets/widgets.dart
lib/models/feature_access/login_mode_action.dart
packages/webtrit_appearance_theme/lib/models/features_config/app_config.dart
packages/webtrit_appearance_theme/lib/models/features_config/app_config.freezed.dart
packages/webtrit_appearance_theme/lib/models/features_config/app_config.g.dart
screenshots/lib/mocks/mock_login_cubit.dart
screenshots/lib/screenshots/login_mode_select_screen_screenshot.dart

•	Simplified configuration for embedded login screens
•	Added support for displaying custom buttons on the welcome screen
•	Enabled defining an embedded launch screen as an alternative to the default welcome screen
_Before releasing a new version with this PR, make sure to update the customer configuration and include the additional properties._

refactor: add correct configuration for embedded signup

---

makefile
tool/run/run-android-deeplinksDisabledsmsReceiver.xml
tool/run/run-android-deeplinksDisabledsmsReceiverDisabled.xml
tool/run/run-android-deeplinkssmsReceiver.xml
tool/run/run-android-deeplinkssmsReceiverDisabled.xml
tool/run/run.xml

Added IntelliJ IDEA run configurations and a Makefile script to simplify working with flavors. Documentation will need to be updated accordingly.

feat: add IDE run configurations for all flavor combinations

---

pubspec.lock
pubspec.yaml
screenshots/pubspec.lock

This issue appears to be related to the webview_flutter package and seems to have been resolved in versions prior to ^4.13.0. We are unable to reproduce the issue on simulators; it only occurs on certain physical devices.

fix: Touch Screen Responsiveness Issues on Embedded Pages (Android)

---

lib/features/user_info/cubit/user_info_cubit.dart
lib/repositories/account/user_repository.dart
packages/webtrit_api/lib/src/exceptions.dart
packages/webtrit_api/lib/src/webtrit_api_client.dart

fix: handle user not found (404) with UserNotFoundException and update usages of getUserInfo to handle this case.

fix: handle user not found (404) with UserNotFoundException

---

lib/extensions/extensions.dart
lib/extensions/rtc_peer_connection_extension.dart
lib/features/call/bloc/call_bloc.dart

fix(WebRTC): add safeAddTrack extension to prevent addTrack crash on closed RTCPeerConnection

fix(WebRTC): Fix RTCPeerConnection addTrack crash

---

assets/themes/app.config.json
docs/embedded_pages.md
lib/app/router/app_router.gr.dart
lib/features/login/view/login_router_page.dart
lib/features/login/view/login_switch_screen.dart
lib/features/login/view/login_switch_screen_page.dart
lib/widgets/web_view_container.dart

Add option to disable safe area for embedded login pages and improve MediaQuery payload structure

feat: improve control of safe area on embedded pages

---

lib/features/login/cubit/login_cubit.dart
lib/features/login/cubit/login_cubit.freezed.dart
lib/features/login/cubit/login_state.dart
lib/features/login/features/login_signup/view/login_signup_embedded_request_screen.dart
lib/features/login/features/login_signup/widgets/embedded_request_error_dialog.dart
lib/features/login/features/login_signup/widgets/widgets.dart

Handles IO vs HTTP errors differently, shows native error UI, supports manual retries, and controls back navigation based on error type.

feat: add retry logic and error UI with back handling for core request failures

---

.github/flutter_version.yaml
docs/build.md

Adds .github/flutter_version.yaml to define the Flutter SDK version used during builds.

feat: introduce flutter version configuration and document build process

---

README.md
docs/development.md
lefthook.yml
lib/features/main/view/main_screen_page.dart
packages/_web_socket_channel/lib/src/_web_socket_channel_html.dart
packages/data/app_database/lib/src/connection/web.dart
packages/data/app_database/test/migrations_test.dart
packages/webtrit_signaling/test/src/factories/fake_webtrit_signaling.dart
packages/webtrit_signaling/test/src/factories/signaling_client_factory_test.dart
screenshots/analysis_options.yaml
tool/scripts/branch-name-check.sh
tool/scripts/commit-msg-check.sh

This PR introduces Lefthook integration to enforce Git commit and branch naming conventions, as well as run automatic lint and test checks on commit and push. It includes scripts for validating commit messages, branch names, and Flutter version consistency.

feat: integrate lefthook for Git hooks management

---

docs/custom_login.md
lib/features/login/features/login_signup/view/login_signup_embedded_request_screen.dart
lib/features/login/features/login_signup/view/login_signup_embedded_request_screen_page.dart
lib/widgets/webview/web_view_container.dart
screenshots/lib/screenshots/login_signup_screen_screenshot.dart

This PR improves custom login page integration by replacing direct JavaScript injection with a more structured injection strategy pattern and consolidating page initialization into a single function. The changes standardize how data is passed to embedded web views and update the corresponding documentation.
Replaced manual JavaScript injection with a configurable PageInjectionStrategy system
Consolidated setLocale() and progress handling into a single initializePage() function
Updated documentation to reflect the new initialization approach

fix: improve custom login page integration with injection strategy and embedded progress handling

---

lib/widgets/webview/web_view_container.dart
test/embedded/soft_reload_recovery_strategy_test.dart

This PR fixes the SoftReloadRecoveryStrategy to skip automatic retries after a successful page load, preventing unnecessary reload attempts when connectivity is restored after an initial success.
- Introduces a _hasSuccessfulLoad flag to track when a page has loaded successfully at least once
- Modifies retry logic to respect this flag and avoid redundant reloads on reconnection
- Resets the flag on explicit page load failures to re-enable retries when needed

fix: skip retries after first successful load in SoftReloadRecoveryStrategy

---

lib/l10n/arb/app_en.arb

This PR adds descriptions to ARB (App Resource Bundle) localization metadata across the entire English localization file. These descriptions provide detailed context about when, where, and why each error message or UI text is displayed to users.

chore: add error message descriptions to ARB files
